KerasJson: example-keras-model-files/KERAS_3layer.json
KerasH5:   example-keras-model-files/KERAS_3layer_weights.h5
InputData: example-keras-model-files/KERAS_3layer_input_features.dat
OutputPredictions: example-keras-model-files/KERAS_3layer_predictions.dat
TruthLabels: example-keras-model-files/KERAS_3layer_truth_labels.dat
OutputDir: my-hls-test-3layer
ProjectName: myproject
XilinxPart: xcvu9p-fsgd2104-2-i

ReuseFactor: 1
DefaultPrecision: ap_fixed<16,6> 
